# Generated by Django 4.2.7 on 2023-12-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitedog',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='sitedog',
            name='slug',
            field=models.SlugField(blank=True, default='exit', max_length=255),
        ),
        migrations.AddIndex(
            model_name='sitedog',
            index=models.Index(fields=['-time_create'], name='sitedog_sit_time_cr_7fb233_idx'),
        ),
    ]
