# Generated by Django 4.2.7 on 2024-01-07 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitedog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedog',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitedog',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='sitedog.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='sitedog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='sitedog.tagpost', verbose_name='Теги'),
        ),
        migrations.AddIndex(
            model_name='sitedog',
            index=models.Index(fields=['-time_create'], name='sitedog_sit_time_cr_7fb233_idx'),
        ),
    ]
