# Generated by Django 4.2.7 on 2023-12-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedog', '0002_alter_sitedog_options_sitedog_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedog',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
