# Generated by Django 4.2.7 on 2023-12-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedog', '0003_alter_sitedog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedog',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
