# Generated by Django 4.2.7 on 2024-05-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-time_create'], 'verbose_name': 'Dog breeds', 'verbose_name_plural': 'Dog breeds'},
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, verbose_name='Slug'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-time_create'], name='article_art_time_cr_f21e29_idx'),
        ),
    ]
