# Generated by Django 4.2.7 on 2024-06-25 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP')),
                ('viewed_on', models.DateTimeField(auto_now_add=True, verbose_name='Date viewed')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='article.article')),
            ],
            options={
                'verbose_name': 'viewing',
                'verbose_name_plural': 'views',
                'ordering': ('-viewed_on',),
                'indexes': [models.Index(fields=['-viewed_on'], name='article_vie_viewed__a2f1dc_idx')],
            },
        ),
    ]
